Import('env')

x11_srcs = Glob('*.d')
_x11_libs = ['X11', 'xcb', 'Xau', 'Xdmcp']

_x11_d_lib = env.Library(
    'Dx11',
    x11_srcs,
    DPATH=['#/src'])

_x11_lib_bundle = _x11_libs + [_x11_d_lib]

Return('_x11_lib_bundle')
