Import('env skia_lib qcheck_lib qcheck_imp x_lib_bundle')

_srcs = Glob('*.d')

app = env.Program('SampleApp',
                  _srcs,
#                  LINKCOM=env['DLINKCOM'],
                  LIBS=[skia_lib, qcheck_lib, x_lib_bundle, 'freetype', 'z'],
                  LINKFLAGS=env['LINKFLAGS']+env['DLINKFLAGS'],
                  DPATH=['#/src', '.', qcheck_imp])
Return('app')
