Import('env skia_lib qcheck_lib qcheck_imp')

_srcs = Glob('*.d')

if env['BUILD_STYLE'] == 'relese':
   _d_link_flags=[File('GuiApp.def')]
else:
   _d_link_flags=[File('ConsoleApp.def')]

app = env.Program('SampleApp',
                  _srcs,
                  LINKCOM=env['DLINKCOM'],
                  DLINKFLAGS=_d_link_flags,
                  LIBS=['#/gdi32', skia_lib, qcheck_lib],
                  DPATH=['#/src', '.', qcheck_imp])
Return('app')
